service: aws-nodejs # NOTE: update this with your service name



provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-2


functions:
  hello:
    handler: handler.hello
    events:
     - http:
        path: users/create
        method: get
  database:
    handler: handler.database
    events:
     - http:
        path: /
        method: get